import { Region, Departement } from '../components/classes/RegDep';




export const Liste_Reg:Region[] =[
  { id: "84", nom: "Auvergne-Rhône-Alpes" },
  { id: "27", nom: "Bourgogne-Franche-Comté" },
  { id: "53", nom: "Bretagne" },
  { id: "24", nom: "Centre-Val de Loire" },
  { id: "94", nom: "Corse" },
  { id: "44", nom: "Grand Est" },
  { id: "32", nom: "Hauts-de-France" },
  { id: "11", nom: "Île-de-France" },
  { id: "28", nom: "Normandie" },
  { id: "75", nom: "Nouvelle-Aquitaine" },
  { id: "76", nom: "Occitanie" },
  { id: "52", nom: "Pays de la Loire" },
  { id: "93", nom: "Provence-Alpes-Côte d’Azur" },
//   Région d'outre mer
  { id: "01", nom: "Guadeloupe" },
  { id: "02", nom: "Martinique" },
  { id: "03", nom: "Guyane" },
  { id: "04", nom: "La Réunion" },
  { id: "06", nom: "Mayotte" }
]


export const Liste_Dep:Departement[] =[
    // Outre Mer
  { id: "971", nom: "Guadeloupe", coord:[16.25,-61.5833] },
  { id: "972", nom: "Martinique", coord:[14.6,-61.0] },
  { id: "973", nom: "Guyane", coord:[4.9,-53.0] },
  { id: "974", nom: "La Réunion", coord:[-21.1,55.5] },
  { id: "976", nom: "Mayotte", coord:[12.8,45.2] },

  // 🇫🇷 France métropolitaine
  { id: "01", nom: "Ain", coord:[46.1,5.2] },
  { id: "02", nom: "Aisne", coord:[49.2,3.5] },
  { id: "03", nom: "Allier", coord:[45.8,3.1] },
  { id: "04", nom: "Alpes-de-Haute-Provence", coord:[44.5,5.8] },
  { id: "05", nom: "Hautes-Alpes", coord:[44.8,6.2] },
  { id: "06", nom: "Alpes-Maritimes", coord:[43.8,7.1] },
  { id: "07", nom: "Ardèche", coord:[45.1,4.8] },
  { id: "08", nom: "Ardennes", coord:[49.7,4.2] },
  { id: "09", nom: "Ariège", coord:[43.1,1.5] },
  { id: "10", nom: "Aube", coord:[48.2,4.3] },
  { id: "11", nom: "Aude", coord:[43.2,2.5] },
  { id: "12", nom: "Aveyron", coord:[44.2,2.3] },
  { id: "13", nom: "Bouches-du-Rhône", coord:[43.5,5.0] },
  { id: "14", nom: "Calvados", coord:[49.2,0.5] },
  { id: "15", nom: "Cantal", coord:[45.0,2.0] },
  { id: "16", nom: "Charente", coord:[45.8,0.7] },
  { id: "17", nom: "Charente-Maritime", coord:[46.2,-1.0] },
  { id: "18", nom: "Cher", coord:[47.2,2.0] },
  { id: "19", nom: "Corrèze", coord:[45.3,1.8] },
  { id: "2A", nom: "Corse-du-Sud", coord:[42.0,9.0] },
  { id: "2B", nom: "Haute-Corse", coord:[42.5,9.5] },
  { id: "21", nom: "Côte-d’Or", coord:[47.0,5.0] },
  { id: "22", nom: "Côtes-d’Armor", coord:[48.5,-3.0] },
  { id: "23", nom: "Creuse", coord:[45.8,1.5] },
  { id: "24", nom: "Dordogne", coord:[45.0,1.0] },
  { id: "25", nom: "Doubs", coord:[47.0,6.5] },
  { id: "26", nom: "Drôme", coord:[45.0,5.0] },
  { id: "27", nom: "Eure", coord:[49.0,1.0] },
  { id: "28", nom: "Eure-et-Loir", coord:[48.5,1.5] },
  { id: "29", nom: "Finistère", coord:[48.0,-4.0] },
  { id: "30", nom: "Gard", coord:[44.0,3.5] },
  { id: "31", nom: "Haute-Garonne", coord:[43.5,1.5] },
  { id: "32", nom: "Gers", coord:[43.5,0.5] },
  { id: "33", nom: "Gironde", coord:[44.5,-0.5] },
  { id: "34", nom: "Hérault", coord:[43.5,3.5] },
  { id: "35", nom: "Ille-et-Vilaine", coord:[48.2,-1.5] },
  { id: "36", nom: "Indre", coord:[47.0,2.0] },
  { id: "37", nom: "Indre-et-Loire", coord:[47.2,1.0] },
  { id: "38", nom: "Isère", coord:[45.0,6.0] },
  { id: "39", nom: "Jura", coord:[46.8,6.0] },
  { id: "40", nom: "Landes", coord:[44.0,-1.0] },
  { id: "41", nom: "Loir-et-Cher", coord:[47.5,1.5] },
  { id: "42", nom: "Loire", coord:[45.5,4.0] },
  { id: "43", nom: "Haute-Loire", coord:[45.0,3.5] },
  { id: "44", nom: "Loire-Atlantique", coord:[47.0,-1.5] },
  { id: "45", nom: "Loiret", coord:[48.0,2.0] },
  { id: "46", nom: "Lot", coord:[44.5,1.5] },
  { id: "47", nom: "Lot-et-Garonne", coord:[43.8,0.5] },
  { id: "48", nom: "Lozère", coord:[44.2,3.8] },
  { id: "49", nom: "Maine-et-Loire", coord:[47.5,-0.5] },
  { id: "50", nom: "Manche", coord:[49.0,0.0] },
  { id: "51", nom: "Marne", coord:[48.5,4.5] },
  { id: "52", nom: "Haute-Marne", coord:[48.0,4.0] },
  { id: "53", nom: "Mayenne", coord:[48.0,-0.5] },
  { id: "54", nom: "Meurthe-et-Moselle", coord:[48.7,6.0] },
  { id: "55", nom: "Meuse", coord:[49.0,3.5] },
  { id: "56", nom: "Morbihan", coord:[47.8,-3.2] },
  { id: "57", nom: "Moselle", coord:[49.2,6.2] },
  { id: "58", nom: "Nièvre", coord:[47.2,3.2] },
  { id: "59", nom: "Nord", coord:[50.5,3.0] },
  { id: "60", nom: "Oise", coord:[49.5,2.5] },
  { id: "61", nom: "Orne", coord:[48.5,0.5] },
  { id: "62", nom: "Pas-de-Calais", coord:[50.5,1.5] },
  { id: "63", nom: "Puy-de-Dôme", coord:[45.8,3.2] },
  { id: "64", nom: "Pyrénées-Atlantiques", coord:[43.2,-0.8] },
  { id: "65", nom: "Hautes-Pyrénées", coord:[43.0,0.2] },
  { id: "66", nom: "Pyrénées-Orientales", coord:[42.8,2.8] },
  { id: "67", nom: "Bas-Rhin", coord:[48.7,7.3] },
  { id: "68", nom: "Haut-Rhin", coord:[48.1,7.1] },
  { id: "69", nom: "Rhône", coord:[45.5,4.5] },
  { id: "70", nom: "Haute-Saône", coord:[47.5,6.0] },
  { id: "71", nom: "Saône-et-Loire", coord:[46.5,4.5] },
  { id: "72", nom: "Sarthe", coord:[48.0,0.0] },
  { id: "73", nom: "Savoie", coord:[45.5,6.5] },
  { id: "74", nom: "Haute-Savoie", coord:[45.8,6.2] },
  { id: "75", nom: "Paris", coord:[48.8,2.3] },
  { id: "76", nom: "Seine-Maritime", coord:[49.3,1.8] },
  { id: "77", nom: "Seine-et-Marne", coord:[48.5,2.8] },
  { id: "78", nom: "Yvelines", coord:[48.3,1.9] },
  { id: "79", nom: "Deux-Sèvres", coord:[46.5,-0.5] },
  { id: "80", nom: "Somme", coord:[49.5,2.0] },
  { id: "81", nom: "Tarn", coord:[43.5,2.0] },
  { id: "82", nom: "Tarn-et-Garonne", coord:[43.8,1.5] },
  { id: "83", nom: "Var", coord:[43.5,5.0] },
  { id: "84", nom: "Vaucluse", coord:[44.0,5.0] },
  { id: "85", nom: "Vendée", coord:[46.5,-1.0] },
  { id: "86", nom: "Vienne", coord:[46.2,1.0] },
  { id: "87", nom: "Haute-Vienne", coord:[46.2,1.7] },
  { id: "88", nom: "Vosges", coord:[48.0,6.5] },
  { id: "89", nom: "Yonne", coord:[47.5,3.0] },
  { id: "90", nom: "Territoire de Belfort", coord:[47.5,6.5] },
  { id: "91", nom: "Essonne", coord:[48.5,2.0] },
  { id: "92", nom: "Hauts-de-Seine", coord:[48.8,2.0] },
  { id: "93", nom: "Seine-Saint-Denis", coord:[48.9,2.3] },
  { id: "94", nom: "Val-de-Marne", coord:[48.7,2.5] },
  { id: "95", nom: "Val-d’Oise", coord:[48.8,2.0] }
]


// Fonction pour retourner le nom d'un département à partir de son code
export const getDepartmentName = (code: string): string => {
  const dept = Liste_Dep.find(d => d.id === code);
  return dept ? dept.nom : "Département inconnu";
};

//  Departement par région 

export const departementToRegion: Record<string, string> = {
      "01": "Auvergne-Rhône-Alpes",
      "03": "Auvergne-Rhône-Alpes",
      "07": "Auvergne-Rhône-Alpes",
      "15": "Auvergne-Rhône-Alpes",
      "26": "Auvergne-Rhône-Alpes",
      "38": "Auvergne-Rhône-Alpes",
      "42": "Auvergne-Rhône-Alpes",
      "43": "Auvergne-Rhône-Alpes",
      "63": "Auvergne-Rhône-Alpes",
      "69": "Auvergne-Rhône-Alpes",
      "73": "Auvergne-Rhône-Alpes",
      "74": "Auvergne-Rhône-Alpes",

      "21": "Bourgogne-Franche-Comté",
      "25": "Bourgogne-Franche-Comté",
      "39": "Bourgogne-Franche-Comté",
      "58": "Bourgogne-Franche-Comté",
      "70": "Bourgogne-Franche-Comté",
      "71": "Bourgogne-Franche-Comté",
      "89": "Bourgogne-Franche-Comté",
      "90": "Bourgogne-Franche-Comté",

      "22": "Bretagne",
      "29": "Bretagne",
      "35": "Bretagne",
      "56": "Bretagne",

      "18": "Centre-Val de Loire",
      "28": "Centre-Val de Loire",
      "36": "Centre-Val de Loire",
      "37": "Centre-Val de Loire",
      "41": "Centre-Val de Loire",
      "45": "Centre-Val de Loire",

      "2A": "Corse",
      "2B": "Corse",

      "08": "Grand Est",
      "10": "Grand Est",
      "51": "Grand Est",
      "52": "Grand Est",
      "54": "Grand Est",
      "55": "Grand Est",
      "57": "Grand Est",
      "67": "Grand Est",
      "68": "Grand Est",
      "88": "Grand Est",

      "02": "Hauts-de-France",
      "59": "Hauts-de-France",
      "60": "Hauts-de-France",
      "62": "Hauts-de-France",
      "80": "Hauts-de-France",

      "75": "Île-de-France",
      "77": "Île-de-France",
      "78": "Île-de-France",
      "91": "Île-de-France",
      "92": "Île-de-France",
      "93": "Île-de-France",
      "94": "Île-de-France",
      "95": "Île-de-France",

      "14": "Normandie",
      "27": "Normandie",
      "50": "Normandie",
      "61": "Normandie",
      "76": "Normandie",

      "16": "Nouvelle-Aquitaine",
      "17": "Nouvelle-Aquitaine",
      "19": "Nouvelle-Aquitaine",
      "23": "Nouvelle-Aquitaine",
      "24": "Nouvelle-Aquitaine",
      "33": "Nouvelle-Aquitaine",
      "40": "Nouvelle-Aquitaine",
      "47": "Nouvelle-Aquitaine",
      "64": "Nouvelle-Aquitaine",
      "79": "Nouvelle-Aquitaine",
      "86": "Nouvelle-Aquitaine",
      "87": "Nouvelle-Aquitaine",

      "09": "Occitanie",
      "11": "Occitanie",
      "12": "Occitanie",
      "30": "Occitanie",
      "31": "Occitanie",
      "32": "Occitanie",
      "34": "Occitanie",
      "46": "Occitanie",
      "48": "Occitanie",
      "65": "Occitanie",
      "66": "Occitanie",
      "81": "Occitanie",
      "82": "Occitanie",

      "44": "Pays de la Loire",
      "49": "Pays de la Loire",
      "53": "Pays de la Loire",
      "72": "Pays de la Loire",
      "85": "Pays de la Loire",

      "04": "Provence-Alpes-Côte d’Azur",
      "05": "Provence-Alpes-Côte d’Azur",
      "06": "Provence-Alpes-Côte d’Azur",
      "13": "Provence-Alpes-Côte d’Azur",
      "83": "Provence-Alpes-Côte d’Azur",
      "84": "Provence-Alpes-Côte d’Azur",

      // Guadeloupe
      "971": "Guadeloupe",
      
      // Martinique
      "972": "Martinique",
      
      // Guyane
      "973": "Guyane",
      
      // La Réunion
      "974": "La Réunion",
      
      // Mayotte
      "976": "Mayotte",
}

